### ISSUE TITLE
Manuál k spuštění pruningu, parametry spouštění úlohy

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#10]

**Comment by hrubysi** [comment]
Dále bych poprosil o manuál jak spustit úlohu s AUTO conf a supp, pokud to má jít

**Comment by vojir** [comment]
Podporovaní míry zajímavosti zadávané do IMs mají identifikátory:
**['CONF','AAD','LIFT','SUPP','AUTO_CONF_SUPP','RULE_LENGTH']**

Pro spuštění prunningu tam pošlete jako vlastnost specialIMs: 
**"specialIMs": {
{"name": "CBA"}
}**

**Comment by vojir** [comment]
jinak použití je ukázané i v tomto příkladu: https://github.com/KIZI/EasyMiner-Documentation/blob/master/EasyMinerCenter%20API%20examples/Association%20rule%20mining.ipynb

(byť tedy v Pythonu)
