### ISSUE TITLE
Zasílání zpráv o průběhu vytváření atributu

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#12]
Poprosil bych o zasílání následujících postMessage zpráv při vytváření atributu:

**Po odkliknutí create attribute**
- Jeden atribut
```
window.parent.postMessage({
  type: 'add-attribute',
  state: 'started',
  columnId: 29550, // id zdrojového sloupce
  attributeName: 'amount_equifrequent_5', // název vytvářeného atributu
});
```
- Více atributů
```
window.parent.postMessage({
  type: 'add-attribute',
  state: 'started',
  columnNames: 'amount,birth_number,District', // jména zdrojových sloupců
});
```

**Po úspěšném vytvoření**
```
window.parent.postMessage({
  type: 'add-attribute',
  state: 'done',
  columnId/columnNames: '...',
});
```

**Pokud nastane při vytváření chyba**
```
window.parent.postMessage({
  type: 'add-attribute',
  state: 'failed',
  columnId/columnNames: '...',
});
```

**Comment by hrubysi** [comment]
Ještě by bylo hezké, kdyby stránky pro iframe (histogram, preprocessign, testovani modelu) po načtení odeslali něco jako následující, a já tak mohl korektně zobrazit načítání iframe.

```
window.parent.postMessage({
  type: 'page-ready',
});
```

**Comment by vojir** [comment]
V rámci vytváření atributů je nově podporována možnost vracení postMessage místo redirectu. Pro povolení je potřeba při zobrazování iframe pro vytváření atributu přidat do URL returnPostMessage=1, tj. například:
https://br-dev.lmcloud.vse.cz/easyminercenter/em/attributes/add-attribute?miner=3178&column=36853&mode=iframe&returnPostMessage=1

následně je zasílána zpráva ve tvaru:
{
    "type": "preprocessing",
    "message": null,
    "state": "in_progress",
    "attributes": [
        {
            "id": 28212,
            "name": "status8",
            "columnId": 36853,
            "columnName": "status"
        }
    ]
}

**Comment by vojir** [comment]
Při zobrazení iframů se v rámci události $(document).ready() nově odesílá postMessage:
{
      type: 'iframe-ready',
    }
