### ISSUE TITLE
Routování public souborů odkazuje na špatnou adresu

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#13]
Nepodařilo se mi přijít na to proč, ale MiningUI a MiningUI2 má odlišné chování při získávání public souborů.

https://br-dev.lmcloud.vse.cz/easyminercenter/_miningUI/js/lib/ColorHelpes.js
The requested URL /easyminercenter/submodules/EasyMiner-MiningUI/web/js/lib/ColorHelpes.js was not found on this server.
https://br-dev.lmcloud.vse.cz/easyminercenter/_miningUI2/js/lib/ColorHelpes.js
The requested URL /easyminercenter/www/submodules/EasyMiner-MiningUI2/public/js/lib/ColorHelpes.js was not found on this server.

MiningUI2 má v adrese navíc **/www/** a tudíž se nenačítají správně JS a CSS soubory.

**Comment by vojir** [comment]
Bylo tam nějaké zvláštní chování redirectů pomocí .htaccessu, aktuálně už načítání souborů z dané složky funguje správně.
např. https://br-dev.lmcloud.vse.cz/easyminercenter/_miningUI2/assets/index-4w9mtj8N.css

**Comment by hrubysi** [comment]
Ještě bych poprosil o opravu cesty CSS zdrojů na řádku 28:
https://github.com/KIZI/EasyMiner-EasyMinerCenter/edit/master/app/EasyMinerModule/templates/MiningUi2/default.latte

(Mohl jsem commitnout změnu, ale nedomluvili jsme se, že bych měl zasahovat do kódu mimo MiningUI2)
