### ISSUE TITLE
Odebrat defaultní layout z MiningUI2

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#14]
Prosím odebrat defaultní layout z MiningUI2, nové UI již okolní layout obsahuje a byl by tam tak dvakrát.

**Comment by vojir** [comment]
Nyní se Vám zobrazení inicializuje v prázdné HTML stránce, ale v praxi to jednak zkomplikuje jednotné vykreslení hlavičky a pak to zabraňuje funkčnosti některých jiných částí (např. EasyMiner-Help).

**Comment by hrubysi** [comment]
Prosím přidat do body prázdný div s id "MiningUI".

---

Původní hlavička bude problém jakmile začnu řešit responsivitu a přidám meta tag pro viewport. Asi bych její styly mohl přepsat, takže je to na domluvě.

Pokud ji zachováme:
- bude konzistentní skrze celý web a nebude se muset duplikovat její funkcionalita
- zároveň ale nebudu mít kontrolu nad konzistentním vizuálním stylem stránky minování a navržený design možná nebude tak dobře fungovat/vypadat

--- 

EasyMiner-Help asi není problém zachovat v obou případech, jen budu muset přidat potřebné selektory.

**Comment by vojir** [comment]
DIV s daným ID doplněn
