### ISSUE TITLE
Přidat možnost nastavení atributu "type" JS v Integration.php

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#16]
Potřeboval bych mít možnost nastavit typ JS souboru v Integration.php na "module".
`<script type="module" src="/easyminercenter/_miningUI2/assets/module.js"></script>`

Příklad konfigurace, která by tomu odpovídala:

```
  public static $javascriptFiles = [
    'config',
    'assets/common.js',
    ['assets/common2.js', 'text/javascript'],
    ['assets/module.js', 'module'],
  ];
```

**Comment by vojir** [comment]
Nově je podporován zápis ve tvaru   public static $javascriptFiles = [
    'config',
    'assets/common.js',
    'assets/common2.js',
    ['src'=>'assets/module.js', 'type'=>'module'],
  ];
