### ISSUE TITLE
Mining nalézá maximálně jedno pravidlo

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#3]
Token: `BKP9yP5QqfXNs198137NlvI4LR33282UQAI07dVXvmybLe6sucf`

Parametry tasku:

```
{
    "IMs": [
        {
            "name": "CONF",
            "value": 0.7
        },
        {
            "name": "SUPP",
            "value": 0.05
        }
    ],
    "antecedent": [
        {
            "attribute": "District"
        },
        {
            "attribute": "status"
        }
    ],
    "consequent": [
        {
            "attribute": "Salary"
        }
    ],
    "miner": 2974,
    "name": "District (*) and status (*) => Salary (*)"
}
```

**Comment by vojir** [comment]
Z mého pohledu dolování normálně funguje. Zkuste nastavení:

{
  "miner": 3178,
  "name": "test task",
  "antecedent": [
    {
      "attribute": "District"
    }
  ],
  "consequent": [
    {
      "attribute": "status"
    }
  ],
  "IMs": [
    {
      "name": "CONF",
      "value": 0.7
    },
    {
      "name": "SUPP",
      "value": 0.01
    }
  ],
  "limitHits": 1000
}

apiKey M61b1vU5hjZ7tlu20364SNXA2V50400ZxMTprvJFllCddYY858X

**Comment by vojir** [comment]
Už vím, v čem je problém - v zadání vám chybí nastavení limitHits, které určuje maximální počet pravidel, které chcete najít. Když ho nezadáte, tak minimální hodnota je 1.
