### ISSUE TITLE
Parametry spuštění tasku

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#4]
[POST](https://br-dev.lmcloud.vse.cz/easyminercenter/api/swagger#!/Tasks/post_tasks_simple) [/tasks/simple](https://br-dev.lmcloud.vse.cz/easyminercenter/api/swagger#!/Tasks/post_tasks_simple)

- Jak povolit pruning?
- Jak nastavit negaci atributu?

**Comment by vojir** [comment]
negace aktuálně zadat nejde (ale můžeme ji asi dodělat)

jinak jde o duplicitu s issue #10
