### ISSUE TITLE
Rozšíření endpointu nalezených pravidel

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#5]
[GET](https://br-dev.lmcloud.vse.cz/easyminercenter/api/swagger#!/Tasks/get_tasks_id_rules) [/tasks/{id}/rules](https://br-dev.lmcloud.vse.cz/easyminercenter/api/swagger#!/Tasks/get_tasks_id_rules)

- Přidat paginaci
- Přidat řazení
  - Specifikovat custom řazení
- Specifikovat a implementovat filtrování

Návrh filtrace:

![image](https://github.com/KIZI/EasyMiner-MiningUI2/assets/22034391/791de0fe-8f9d-4732-8aba-e42df92ea441)

```
{
    "confidence": {
        "from": 0.5,
        "to": 1
    },
    "support": {
        "from": 0.1,
        "to": 0.5
    },
    "lift": {
        "from": 0,
        "to": 5
    },
    "antecedent": [
        {
            "id": 29546,
            "values": [] // prázdné -> any value
        },
        {
            "id": 29547,
            "values": ["10-20", "40-50"] // nějaký identifikátor zvolených intervalů
        }
    ],
    "consequent": [
        {
            "id": 29547,
            "values": []
        }
    ],
    "anyCedent": [
        {
            "id": 29549,
            "values": []
        }
    ]
}
```

**Comment by hrubysi** [comment]
- Tady jsme se domluvili pouze na řazení a textovém vyhledávání antecedentu a consequentu.
![image](https://github.com/KIZI/EasyMiner-MiningUI2/assets/22034391/bf6d3b0e-cd59-4c5c-b354-f4b9bc66cc39)

**Comment by vojir** [comment]
Endpoint **/tasks/{id}/rules** je rozšířen o možnost vyhledávání v textu, zadání řazení, stránkování a filtrování podle hodnot měr zajímavosti

**Comment by vojir** [comment]
@hrubysi máte tam doplněné ještě oddělené parametry pro vyhledávání v antecedentu a consequentu pravidla

**Comment by hrubysi** [comment]
@vojir Po vyzkoušení i přímo ve Swaggeru docházím k závěru, že spolehlivě funguje pouze filtrování dle měr zajímavosti.
Textové vyhledávání ani řazení mi nefunguje.

`https://br-dev.lmcloud.vse.cz/easyminercenter/api/tasks/30292/rules?orderby=conf&order=DESC&searchConsequent=salary`

**Comment by vojir** [comment]
@hrubysi To bude tím, že v úloze s ID 30292 žádné pravidlo se salary v consequentu není. Podle zadání úlohy jste měl salary v antecedentu, v consequentu máte "district".
