### ISSUE TITLE
Selected rules

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#6]
- paginace
- řazení
- textové vyhledávání

**Comment by hrubysi** [comment]
Pokud by to nebyl problém, můžeme ještě doplnit míry zajímavosti, aby to bylo konzistentní s nalezenými pravidly.

**Comment by vojir** [comment]
@hrubysi míry zajímavosti se v pravidlech zobrazují, ale pokud by byly všechny rovny 0, tak je nevypisujte (protože může jít o pravidlo z rule editoru, pro které míry zajímavosti nevíme)

**Comment by vojir** [comment]
dokumentace je na https://br-dev.lmcloud.vse.cz/easyminercenter/api#!/RuleSets/get_rule_sets_id_rules
