### ISSUE TITLE
Task history

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#7]
- Získání historie tasků pro daný miner + paginace
  - id
  - name
  - date
  - confidence
  - support
  - lift
  - rule length
  - rule pruning
- Odstranění tasku 

Poté bude potřeba nějak získat strukturu pravidla po rozkliknutí - pro načtení do editoru.

**Comment by vojir** [comment]
Rozšířil jsem popis detailů úlohy o míry zajímavosti, řazení a stránkování, seznam úloh z historie jde získat pomocí /api/miners/{id}/tasks
Pro popis viz https://br-dev.lmcloud.vse.cz/easyminercenter/api#!/Miners/get_miners_id_tasks

Získání detailu úlohy (jejího zadání atp.) je na https://br-dev.lmcloud.vse.cz/easyminercenter/api#!/Tasks/get_tasks_id

--
S odstraněním úlohy je to z hlediska implementace komplikovanější, ale popis volání je v popisu API.

**Comment by hrubysi** [comment]
- Task history umožňuje paginaci, ale nevrací celkový počet (nemohu počítat stránky a poznat, jaká je poslední).
- ⁠[DELETE](https://br-dev.lmcloud.vse.cz/easyminercenter/api/swagger#!/RuleSets/delete_rule_sets_id) mi sice vrací 200, ale task poté v historii stále vidím

**Comment by hrubysi** [comment]
Také jsem zapomněl zmínit, že bych potřeboval mít možnost získat pouze úlohy, které jsou dokončené.
V tuto chvíli tam jsou všechna a mohu je filtrovat pouze lokálně, čímž by ale přestala fungovat paginace.

**Comment by vojir** [comment]
doplněno do endpointu **/miners/{id}/tasks**
