### ISSUE TITLE
Autentizace uživatele

### ISSUE THREAD

**Issue by hrubysi** [KIZI/EasyMiner-MiningUI2#9]
K používání nového API je zapotřebí API TOKEN.
Po přihlášení uživatele v EasyMineru bude třeba při přesměrování do MiningUI předat tento token pomocí JS proměnné.

**Comment by vojir** [comment]
Daný API klíč nově máte v proměnné **userApiKey**.

Jinak případně není problém spustit inicializaci frontendu a při ní rovnou předat API klíč i jinak než přes globální proměnnou.
